name: CI/CD - Stage Environment

on:
  push:
    branches: [stage]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Set image tag
        id: set_tag
        run: echo "image_tag=${{ secrets.DOCKER_USERNAME }}/hello-api-stage:latest" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (not pushed yet)
        run: docker build -t ${{ steps.set_tag.outputs.image_tag }} .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-api-stage:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-api-stage:latest

      - name: Optional: Notify Render to Deploy
        run: echo "✅ Image pushed. Auto-deploy handled by Render webhook."
